version: "3.8"

services:
  auth_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - ecommerce_net
    # Agregar healthcheck
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  auth_service:
    build:
      context: ./src/modules/auth_service
    container_name: auth_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://user:password@auth_db:3306/auth_db
      SECRET_KEY: mi_clave_secreta
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      auth_db:
        condition: service_healthy # Esperar a que la DB est√© saludable
    networks:
      - ecommerce_net
    # Agregar restart para reintentos
    restart: on-failure

volumes:
  auth_db_data:

networks:
  ecommerce_net:
